version: "3"
services:
    nginx:
        image: nginx:alpine
        ports:
            - "127.0.0.1:80:80"
        volumes:
            - "./:/wwwroot"
            - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro"
        links:
            - php
        depends_on:
            - php
    php:
        image: php:fpm-alpine
        volumes:
            - "./:/wwwroot"
            - "./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro"
